Course/urls.py
from django.urls import path,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

handler404 = 'utils.views.custom_404'
handler500 = 'utils.views.custom_500'

def trigger_error(request):
    division_by_zero = 1 / 0
    return division_by_zero

urlpatterns = [
	path('sentry-debug/', trigger_error),
	path('admin/', admin.site.urls),
	path('accounts/', include('Users.urls')),
	path('stock/', include('Stock.urls')),
	path('course/', include('Courseapp.urls')),
	path('tiers/', include('Tiers.urls')),
	path('rewards/', include('Rewards.urls')),
	path('', include('utils.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Stock/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

urlpatterns: list[URLPattern] = [
    path("", views.stock_list, name="stock_list"),
    path("stock-data/<str:symbol>/",views.stock_detail, name="stock_detail"),
    path("watch/<str:symbol>/", views.start_watching_stock, name="watch_stock"),
    path("unwatch/<str:symbol>/", views.stop_watching_stock, name="unwatch_stock"),
    path("fetch-realtime/<str:symbol>/", views.get_realtime_stock_data, name="fetch_realtime_stock_data"),
    path("get_historical_prices/<str:symbol>/<str:duration>/", views.get_historical_stock_data, name="fetch_historical_stock_data")
]

Courseapp/models.py
from typing import Literal
import uuid
from django.db import models
from django.core.exceptions import ValidationError
from requests import Response
from utils.media_handler import MediaHandler
from decimal import Decimal
from utils.utils import generate_quiz_from_content
from utils.decorators import check_load_time, retry_on_failure
from .model_manager import *
from django.utils import timezone

def validate_discount(value) -> None:
    if value < 0:
        raise ValidationError("Discount price must be non-negative.")
    
class Language(models.Model):
    name = models.CharField(max_length=20, unique=True)
    symbol = models.CharField(max_length=5, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    extra_fields = models.JSONField(blank=True, null=True, default=dict)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class Course(models.Model):
    course_uuid = models.UUIDField(unique=True, editable=False, blank=True, null=True)
    course_code = models.CharField(max_length=20, unique=True, blank=True, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    course_type = models.CharField(max_length=10, choices=[('free', 'Free'), ('paid', 'Paid')], default='free')
    course_level = models.CharField(
        max_length=15,
        choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All')],
        default='beginner'
    )
    learning_objectives = models.JSONField(default=list, blank=True, null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, related_name='courses', blank=True, null=True)
    instructor = models.ForeignKey('Users.Instructor', on_delete=models.CASCADE, related_name='courses') # Circular import fixed by using string
    thumbnail = models.ImageField(upload_to='course_thumbnails', blank=True, null=True)
    sections = models.ManyToManyField('Section', related_name='courses', blank=True)
    intro_video = models.FileField(upload_to='intro_videos', blank=True, null=True)
    tags = models.ManyToManyField('Tag', related_name='courses', blank=True)
    prerequisites = models.TextField(blank=True, null=True)
    circulam = models.TextField(blank=True, null=True)
    faqs = models.ManyToManyField('FAQ', related_name='courses', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    discount_price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0, validators=[validate_discount])
    is_published = models.BooleanField(default=False)
    is_open_to_all = models.BooleanField(default=True)
    required_points = models.PositiveIntegerField(default=0, help_text="Required Points to Unlock the scores")
    is_bought_by_users = models.ManyToManyField('Users.Profile', related_name='bought_courses', blank=True)
    bookmarked_by_users = models.ManyToManyField('Users.Profile', related_name='bookmarked_courses', blank=True)
    completed_by_users = models.ManyToManyField('Users.Profile', related_name='completed_courses', blank=True)
    reviews = models.ManyToManyField('CourseReview', related_name='courses', blank=True)
    qr_code = models.ImageField(upload_to='qr_codes/', blank=True, null=True)
    referred_by = models.ManyToManyField('Users.Profile', related_name='referred_courses', blank=True)
    is_deleted = models.BooleanField(default=False)
    is_class_room_course = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    extra_fields = models.JSONField(blank=True, null=True, default=dict)

    objects = CourseManager()  # Default manager
    all_objects = models.Manager()  # Optional: to access deleted too

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title
    
    @check_load_time
    @retry_on_failure(retries=3, delay=2)
    def generate_qr(self, ref="outside", auto_save=False):
        import qrcode
        from io import BytesIO
        from django.core.files.base import ContentFile

        if self.instructor:
            ref = str(self.instructor.profile.user.username)  # force string

        url = f"https://calsie.com.au/course/course/{self.pk}/?ref={ref}"

        qr = qrcode.make(url)
        buffer = BytesIO()
        qr.save(buffer, format="PNG")

        # Ensure title is string before slicing
        title_str = str(self.title) if self.title else "course"
        filename = f"{title_str[:10]}-qr.png"

        self.qr_code.save(filename, ContentFile(buffer.getvalue()), save=False)

        if auto_save:
            super(Course, self).save(update_fields=['qr_code'])


    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('course_detail', kwargs={'pk': self.pk})


    @check_load_time
    @retry_on_failure(retries=3, delay=2)
    def save(self, create_qr=False, enable_ad_revenue = False, *args, **kwargs):
        self.extra_fields['last_updated'] = str(self.updated_at)
        self.extra_fields['is_active'] = self.is_published

        is_new_or_changed = False

        if self.pk:
            old = type(self).objects.filter(pk=self.pk).first()
            if old and old.intro_video != self.intro_video:
                is_new_or_changed = True
        else:
            is_new_or_changed = bool(self.intro_video)

        try:
            price = Decimal(self.price)
            discount_price = Decimal(self.discount_price)
            if price > 0:
                discount_percentage: Decimal = round(((price - discount_price) / price) * 100, 2)
            else:
                discount_percentage = 0
            self.extra_fields['discount_percentage'] = float(discount_percentage)
        except Exception as e:
            print(f"Error calculating discount percentage: {e}")
            self.extra_fields['discount_percentage'] = 0  # Or handle it as needed

        # if self.intro_video and not (
        #     self.intro_video.name.endswith("_optimized.mp4")
        #     or self.intro_video.name.endswith("_resized.mp4")
        # ):
        #     optimized_path = MediaHandler.optimize_video(self.intro_video)
        #     if optimized_path:
        #         MediaHandler.delete_media_file(self.intro_video.name)
        #         self.intro_video = optimized_path

        # Removed MediaHandler import and usage to fix circular import issue
        # from utils.media_handler import MediaHandler

        if not self.qr_code and create_qr:
            self.generate_qr(auto_save=False)
        super().save(*args, **kwargs)

        if self.thumbnail and '_resized' not in self.thumbnail.name:
            resized_path = MediaHandler.resize_image(self.thumbnail, size=(150, 150))
            if resized_path:
                self.thumbnail = resized_path

        if is_new_or_changed and self.intro_video:
            if not self.intro_video.name.endswith("_optimized.mp4") or '_optimized' not in self.intro_video.name:
                optimized_path = MediaHandler.optimize_video(self.intro_video)
                if optimized_path:
                    # delete original unoptimized file
                    MediaHandler.delete_media_file(self.intro_video.name)
                    self.intro_video = optimized_path
                    super().save(update_fields=["intro_video","thumbnail"])

    def delete(self, *args, **kwargs):
        # Delete the associated media files when the model instance is deleted
        # Removed MediaHandler import and usage to fix circular import issue
        # from utils.media_handler import MediaHandler
        if self.thumbnail:
            MediaHandler.delete_media_file(self.thumbnail.name)
        if self.intro_video:
            MediaHandler.delete_media_file(self.intro_video.name)
        if self.qr_code:
            MediaHandler.delete_media_file(self.qr_code.name)
        super().delete(*args, **kwargs)


class Section(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(blank=True, null=True)
    order = models.PositiveIntegerField(default=0)
    is_open = models.BooleanField(default=True)
    article = models.ForeignKey('Article', on_delete=models.SET_NULL, related_name='sections', blank=True, null=True)
    lesson = models.ManyToManyField('Lesson', related_name='sections', blank=True)
    is_deleted = models.BooleanField(default=False)
    instructor = models.ForeignKey('Users.Instructor', on_delete=models.CASCADE, related_name='sections', default=1)
    extra_fields = models.JSONField(blank=True, null=True, default=dict)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = SectionManager()
    all_objects = models.Manager()

    def __str__(self):
        return self.title + " - Open? " + str(self.is_open)
    
    class Meta:
        ordering: list[str] = ['order']
    
    @check_load_time
    @retry_on_failure(retries=3, delay=2)
    def save(self, prompt='', is_generate_content_using_ai=False,*args, **kwargs):
        self.extra_fields['last_updated'] = str(self.updated_at)
        if not self.instructor:
            raise ValueError("Instructor is required")
        # Generate quiz from the first lesson's content if it exists
        if is_generate_content_using_ai:
            related_quizes = Quiz.objects.filter(section=self)
            if not related_quizes.exists():
                quiz_data = generate_quiz_from_content(self.title, self.lesson.first().content if self.lesson.exists() else '', prompt=prompt)
                if quiz_data:
                        quiz = Quiz.objects.create(
                            section=self,
                            title=f"{self.title} Quiz",
                            questions=quiz_data,

templates/course/components/accordian_sidebar.html
<div class="accordion" id="stepsAccordion">
      <div class="accordion-item">
        <h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#steps-collapse" aria-expanded="true" aria-controls="steps-collapse-1">Creation Steps</button></h2>
        <div id="steps-collapse" class="accordion-collapse collapse show" data-bs-parent="#stepsAccordion">
        <div class="accordion-body">
      {% include 'course/components/sidebar.html' with step=step course=course %}
        </div>
        </div>
      </div>
      </div>

      <!-- View Demo -->
      {% if course %}
      <div class="accordion" id="viewDemoAccordion">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#view-demo-collapse" aria-expanded="false" aria-controls="view-demo-collapse">
              View Live Demo
            </button>
          </h2>
          <div id="view-demo-collapse" class="accordion-collapse collapse" data-bs-parent="#viewDemoAccordion">
            <div class="accordion-body">
              <div style="border: 1px solid #ccc; border-radius: 10px; width: 95%; height: 667px; overflow: hidden; margin: auto;">
                <iframe src="{% url 'course_detail' course.pk %}" style="width: 100%; height: 100%; border: none;"></iframe>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endif %}


      <!-- View Creation Demo -->
      <div class="accordion" id="videoDemoAccordion">
      <div class="accordion-item">
        <h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#video-demo-collapse" aria-expanded="false" aria-controls="video-demo-collapse-1">Video Demo</button></h2>
        <div id="video-demo-collapse" class="accordion-collapse collapse" data-bs-parent="#videoDemoAccordion">
        <div class="accordion-body">
          <a href="https://www.youtube.com/watch?v=example" target="_blank" class="btn btn-primary w-100 mb-3">
            {% comment %} <i class="ph ph-youtube-logo me-2"></i> Watch Video Demo {% endcomment %}
            <div class="mt-2 p-3">
              <i class="ph ph-youtube-logo me-2 display-4"></i>
              <br>
              <strong> Watch Video Demo</strong><br>
              A great title and description helps your course get discovered.
            </div>
          </a>
          
        </div>
        </div>
      </div>
      </div>
      
      <div class="mt-2 p-3 bg-secondary text-white rounded">
        <strong>💡 Pro Tip</strong><br>
        A great title and description helps your course get discovered.
      </div>

templates/course/components/course_card.html
<a href="{% url 'course_detail' pk=course.id %}" class="card-link-wrapper" style="text-decoration: none;">
  <div class="card" style="width: 17.85rem;">
      <!-- Thumbnail or Placeholder -->
      {% if course.thumbnail %}
      <img src="{{ course.thumbnail.url }}" class="card-img-top" alt="Course Thumbnail" style="aspect-ratio: 16/9; object-fit: cover;" width="600" height="250">
      <div class="card-img-overlay d-flex flex-column justify-content-start align-items-end">
        {% if course.instructor.profile.user.id == request.user.id %}
        <div class="btn-group" role="group" aria-label="Basic example">
          <a href="{% url 'course_detail' pk=course.id %}" class="btn btn-sm btn-secondary"> View </a>
          <button type="button" data-bs-toggle="offcanvas" data-bs-target="#course-sidebar-{{course.id}}" class="btn btn-sm btn-secondary"> Preview </button>
          <a href="{% url 'course_create_step_one' course_id=course.id %}" class="btn btn-sm btn-primary"> Edit </a>
        </div>
        {% else %}
        {% endif %}
      </div>
      {% else %}
      <svg class="bd-placeholder-img card-img-top" style="aspect-ratio: 16/9; object-fit: cover;" width="600" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">No Thumbnail</text></svg>
      {% endif %}

      <div class="card-body d-flex flex-column">
        <!-- <h1 class="card-text mt-2 mx-auto text-success text-start"><b>{{ course.get_course_type_display }}</b></h1> -->
        <div class="d-flex justify-content-start align-items-center">
        {% for tag in course.tags.all %} 
        <span class="badge m-1 selected-lesson text-dark" style="background-color: {{ tag.extra_fields.bgColor }};color: {{ tag.extra_fields.color }}" data-lesson-id="{{ tag.id }}">
          <i class="{{ tag.extra_fields.icon }}" style="color: {{ tag.extra_fields.iconColor }}"></i> {{ tag.name }}
        </span>
        {% empty %}
        <span class="badge bg-secondary m-1"></span>
        {% endfor %}
      </div>
        <h5 class="card-title mb-2">{{ course.title }}</h5>
        {% if course.course_type == 'free' %}
        <p class="card-text fs-5 d-flex align-items-center">
          <strong class="text-success-emphasis me-2 fs-4">Free</strong>
          <s class="fs-6 text-body-secondary">{% if course.price and course.price != 0 %}{{course.price}}{% endif %}</s>
        </p>
        {% else %}
        <p class="card-text fs-5 d-flex align-items-center">
          {% if course.discount_price and course.discount_price < course.price %}
          <strong class="text-success-emphasis me-2">${{ course.discount_price }}</strong>
          <s class="fs-6 text-body-secondary">${{ course.price }}</s>
          {% elif course.price %}
          <strong class="text-success-emphasis me-2">${{ course.price }}</strong>
          {% else %}
          <strong class="text-success-emphasis me-2">Price not available</strong>
          {% endif %}
        </p>
        {% endif %}
        <!-- Clamp the description visually (CSS below) -->
        <p class="card-text description-clamp mb-2 text-wrap" style="flex: 1 1 auto; min-height: 0;">
          {{ course.description|striptags|truncatechars:35 }}
        </p>
        <div class="d-flex hstack gap-3 mt-auto">
            <div>{{ course.get_course_level_display }}</div>
            <div class="vr"></div>
            <div>{{ course.sections.count }} Sections</div>
            <div class="vr"></div>
            <div>{{ course.language.name|default:"English" }}</div>
        </div>
    </div>
      </div>
</a>

{% comment %} <button type="button" data-bs-toggle="offcanvas" data-bs-target="#example-offcanvas-2" class="card-link-wrapper rounded-2 " style="width: 17rem; text-decoration: none; background-color: transparent; border: none;">
  <div class="card" style="width: 17rem;">
      <!-- Thumbnail or Placeholder -->
      {% if course.thumbnail %}
      <img src="{{ course.thumbnail.url }}" class="card-img-top" alt="Course Thumbnail" style="aspect-ratio: 16/9; object-fit: cover;" width="600" height="250">
      <div class="card-img-overlay d-flex flex-column justify-content-start align-items-end">
        {% if course.instructor.profile.user.id == request.user.id %}
        <div class="btn-group" role="group" aria-label="Basic example">
          <a href="{% url 'course_detail' pk=course.id %}" class="btn btn-sm btn-secondary"> View </a>
          <a href="{% url 'course_create_step_one' course_id=course.id %}" class="btn btn-sm btn-primary"> Edit </a>
        </div>
        {% else %}
        {% endif %}
      </div>
      {% else %}
      <svg class="bd-placeholder-img card-img-top" style="aspect-ratio: 16/9; object-fit: cover;" width="600" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">No Thumbnail</text></svg>
      {% endif %}

      <div class="card-body d-flex flex-column">
        <!-- <h1 class="card-text mt-2 mx-auto text-success text-start"><b>{{ course.get_course_type_display }}</b></h1> -->
        <div class="d-flex justify-content-start align-items-center">
        {% for tag in course.tags.all %} 
        <span class="badge m-1 selected-lesson text-dark" style="background-color: {{ tag.extra_fields.bgColor }};color: {{ tag.extra_fields.color }}" data-lesson-id="{{ tag.id }}">
          <i class="{{ tag.extra_fields.icon }}" style="color: {{ tag.extra_fields.iconColor }}"></i> {{ tag.name }}
        </span>
        {% empty %}
        <span class="badge bg-secondary m-1"></span>
        {% endfor %}
      </div>
        <h5 class="card-title mb-2">{{ course.title }}</h5>
        {% if course.course_type == 'free' %}
        <p class="card-text fs-5 d-flex align-items-center">
          <strong class="text-success-emphasis me-2">Free</strong>
          <s class="fs-6 text-body-secondary">{% if course.price and course.price != 0 %}{{course.price}}{% endif %}</s>
        </p>
        {% else %}
        <p class="card-text fs-5 d-flex align-items-center">
          {% if course.discount_price and course.discount_price < course.price %}
          <strong class="text-success-emphasis me-2">${{ course.discount_price }}</strong>
          <s class="fs-6 text-body-secondary">${{ course.price }}</s>
          {% elif course.price %}
          <strong class="text-success-emphasis me-2">${{ course.price }}</strong>
          {% else %}
          <strong class="text-success-emphasis me-2">Price not available</strong>
          {% endif %}
        </p>
        {% endif %}
        <!-- Clamp the description visually (CSS below) -->
        <p class="card-text description-clamp mb-2" style="flex: 1 1 auto; min-height: 0;">
          {{ course.description|striptags|truncatechars:75 }}
        </p>
        <div class="d-flex hstack gap-3 mt-auto">
            <div>{{ course.get_course_level_display }}</div>
            <div class="vr"></div>
            <div>{{ course.sections.count }} Sections</div>
            <div class="vr"></div>
            <div>{{ course.language.name|default:"English" }}</div>
        </div>
    </div>
      </div>
    </button> {% endcomment %}

templates/course/components/course_notes_list.html
{% for note in course_notes %}
    {% if lesson and note.lesson.id == lesson.id %}
    <div class="card border-secondary mb-3" 
         hx-get="{% url 'fetch_realtime_notes' course_id=note.course.id section_id=note.section.id lesson_id=note.lesson.id %}" 
         hx-trigger="every 5s" 
         hx-swap="outerHTML">
        <div class="card-header text-muted d-flex justify-content-between">
            <span><b>{{ note.user.profile.user.first_name }}</b></span>
            <small>{{ note.created_at|timesince }} ago</small>
        </div>
        <div class="card-body">
            <p class="card-text">{{ note.note_text }}</p>
        </div>
    </div>
    {% endif %}
{% empty %}
    <p class="text-muted">No notes for this lesson yet.</p>
{% endfor %}

templates/course/components/course_sidebar.html
{% load course_tags %}
<div class="offcanvas offcanvas-end p-3" data-bs-scroll="true" data-bs-backdrop="false"
     tabindex="-1" style="width: 40vh;"
     id="course-sidebar-{{course.id}}" aria-labelledby="offcanvas-title-{{course.id}}">

  <!-- Header -->
  <div class="offcanvas-header border-0 p-1">
    <h5 class="offcanvas-title font-weight-bold" id="offcanvas-title-{{course.id}}">
      Preview Details
    </h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>

  <!-- Body -->
  <div class="offcanvas-body p-2 d-flex flex-column h-full">

    <!-- Top Banner / Image -->
    <div class="position-relative">
      {% if course.thumbnail %}
        <img src="{{ course.thumbnail.url }}" alt="{{ course.title }}" 
             class="w-full d-block" style="aspect-ratio: 16/9; object-fit: fill; width: 100%; height: auto;">
      {% else %}
        <svg class="bd-placeholder-img card-img-top w-full" style="aspect-ratio: 16/9; object-fit: cover;"
             xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" 
             preserveAspectRatio="xMidYMid slice" focusable="false">
          <title>No Thumbnail</title>
          <rect width="100%" height="100%" fill="#55595c"></rect>
          <text x="50%" y="50%" fill="#eceeef" dy=".3em" text-anchor="middle">No Thumbnail</text>
        </svg>
      {% endif %}

      {% if course.price %}
      <span class="badge {% if course.course_type == 'free' %} bg-success {% else %} badge-dark {% endif %}   font-weight-semibold position-absolute" 
            style="top: 10px; right: 10px; font-size: 0.9rem; padding: 6px 10px; border-radius: 50px;">
        {% if course.course_type == 'free' %} Free {% else %} {{ course.price }} {% endif %} 
      </span>
      {% endif %}
    </div>

    <!-- Course Info -->
    <div class="flex p-2" style="height: 50vh;">
      <h6 class="font-weight-bold fs-3 mb-1">{{ course.title }}</h6>
      <p class="text-muted mb-2">
        {{ course.description|striptags }}
      </p>
      <hr class="my-4"> 

      <!-- Highlights -->
      {% if course.learning_objectives %}
      <h5 class="font-weight-bold mb-2 mt-3">What you'll learn</h5>
      <ul class="list-unstyled mb-4">
        {% with objectives=course.learning_objectives %}
          {% for item in objectives %}
          <li class="d-flex align-items-center">
            <i class="ph ph-check text-success me-2"></i>
            <span>{{ item }}</span>
          </li>
          {% endfor %}
        {% endwith %}
      </ul>
      <hr class="my-4"> 
      {% endif %}

      <!-- Instructors -->
      {% if course.instructor %}
      <div class="mt-2">
        <h6 class="font-weight-semibold">Instructors</h6>
        <div class="d-flex align-items-center">
          {% with initials=course.instructor.profile|get_initials %}
            <img
              src="{% if course.instructor.profile.avatar %}
                    {{ course.instructor.profile.avatar.url }}
                  {% else %}
                    https://placehold.co/40x40/EBF1FF/7F9CF5?text={{ initials }}
                  {% endif %}"
              alt="{{ course.instructor.profile.user.get_full_name|default:course.instructor.profile.user.username }}"
              class="rounded-circle mr-5"
              style="width:36px;height:36px;object-fit:cover;"
            >
          {% endwith %}


          <p class="font-weight-semibold ms-2">{{ course.instructor.profile.user.get_full_name|default:course.instructor.profile.user.username }}</p>
        </div>
      </div>
      {% endif %}

      <!-- Stats -->
      {% comment %} <div class="d-flex gap-10">
        <div class="bg-light-dark rounded p-10 text-center flex-1">
          <div class="font-weight-bold">{{ course.sections.count|default:'0' }}</div>
          <small class="text-muted">Sections</small>
        </div>
        <div class="bg-light-dark rounded p-10 text-center flex-1">
          <div class="font-weight-bold">{{ course.sections.lesson.count|default:'0h' }}</div>
          <small class="text-muted">Practice</small>
        </div>
      </div> {% endcomment %}
      <hr class="my-4"> 
    </div>

    <!-- Footer Button -->
    <div class="pt-2 border-top">
      <a href="{% url 'course_detail' pk=course.id %}" class="btn btn-primary w-full font-weight-semibold">
        View Course
      </a>
    </div>

  </div>
</div>

templates/course/components/static_testimonials.html
<div id="testimonialCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="row justify-content-center g-3">
                <div class="col-md-4">
                    <div class="card h-100 shadow-sm">
                        <div class="card-body">
                            <p class="card-text">"This course was fantastic! Highly recommended for anyone looking to get started with stocks."</p>
                            <footer class="blockquote-footer mt-2">Jane Doe</footer>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-none d-md-block">
                    <div class="card h-100 shadow-sm">
                        <div class="card-body">
                            <p class="card-text">"Learned so much about the stock market. Great for beginners."</p>
                            <footer class="blockquote-footer mt-2">John Smith</footer>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-none d-md-block">
                    <div class="card h-100 shadow-sm">
                        <div class="card-body">
                            <p class="card-text">"The instructor was clear and concise. A++."</p>
                            <footer class="blockquote-footer mt-2">Emily Jones</footer>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Second Slide -->
        <div class="carousel-item">
            <div class="row justify-content-center g-3">
                <div class="col-md-4">
                    <div class="card h-100 shadow-sm">
                        <div class="card-body">
                            <p class="card-text">"I finally understand the basics of trading and feel confident enough to start investing."</p>
                            <footer class="blockquote-footer mt-2">Maria Garcia</footer>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-none d-md-block">
                    <div class="card h-100 shadow-sm">
                        <div class="card-body">
                            <p class="card-text">"The practical examples were the best part."</p>
                            <footer class="blockquote-footer mt-2">Chen Wang</footer>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 d-none d-md-block">
                    <div class="card h-100 shadow-sm">
                        <div class="card-body">
                            <p class="card-text">"Exceeded all my expectations!"</p>
                            <footer class="blockquote-footer mt-2">Sam Wilson</footer>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#testimonialCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#testimonialCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>